FROM ubuntu:14.04

RUN apt-get update

RUN apt-get -y install python3
RUN apt-get -y install python3-pip

# virutalenv를 해주어야하나...

RUN pip3 install flask
RUN pip3 install flask-sqlalchemy
RUN pip3 install flask-core
